web-hook-link: ""

black-market:
  reset: 30 #in seconds
  chance: 0.5 #chance of item ending up in black market
  message:
    - "&a&lThe black market has been reset!"

mongo:
  uri-mode: false
  normal:
    host: 127.0.0.1
    port: 27017
    auth:
      enabled: false
      username: ''
      password: ''
  uri:
    database: Marketplace
    connection-string: mongodb://127.0.0.1:27017/Marketplace